// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForAddRedemptions implements pgx.CopyFromSource.
type iteratorForAddRedemptions struct {
	rows                 []AddRedemptionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddRedemptions) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddRedemptions) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].CouponID,
		r.rows[0].Status,
		r.rows[0].ResponseMessage,
	}, nil
}

func (r iteratorForAddRedemptions) Err() error {
	return nil
}

func (q *Queries) AddRedemptions(ctx context.Context, arg []AddRedemptionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"redemptions"}, []string{"user_id", "coupon_id", "status", "response_message"}, &iteratorForAddRedemptions{rows: arg})
}
