// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupons.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const addCoupon = `-- name: AddCoupon :exec
INSERT INTO Coupons (code) VALUES ($1) ON CONFLICT (code) DO NOTHING
`

func (q *Queries) AddCoupon(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, addCoupon, code)
	return err
}

const deleteCouponById = `-- name: DeleteCouponById :exec
DELETE FROM Coupons WHERE id = $1
`

func (q *Queries) DeleteCouponById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCouponById, id)
	return err
}

const getAllCoupons = `-- name: GetAllCoupons :many
SELECT id, code, status, first_seen_at, updated_at FROM Coupons
`

func (q *Queries) GetAllCoupons(ctx context.Context) ([]Coupon, error) {
	rows, err := q.db.QueryContext(ctx, getAllCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Coupon
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Status,
			&i.FirstSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, code, status, first_seen_at, updated_at FROM Coupons WHERE code = $1
`

func (q *Queries) GetCouponByCode(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCouponByCode, code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Status,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCouponStatus = `-- name: UpdateCouponStatus :exec
UPDATE Coupons SET 
    status = $1, 
    updated_at = NOW()
WHERE
    id = $2
`

type UpdateCouponStatusParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateCouponStatus(ctx context.Context, arg UpdateCouponStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCouponStatus, arg.Status, arg.ID)
	return err
}
