// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: discord_users.sql

package database

import (
	"context"
)

const addDiscordUser = `-- name: AddDiscordUser :exec
INSERT INTO discord_users (username, discord_id) 
VALUES ($1, $2) ON CONFLICT (discord_id) DO NOTHING
`

type AddDiscordUserParams struct {
	Username  string
	DiscordID int32
}

func (q *Queries) AddDiscordUser(ctx context.Context, arg AddDiscordUserParams) error {
	_, err := q.db.Exec(ctx, addDiscordUser, arg.Username, arg.DiscordID)
	return err
}
