// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Coupon struct {
	ID          uuid.UUID
	Code        string
	Status      string
	FirstSeenAt time.Time
	UpdatedAt   time.Time
}

type DiscordUser struct {
	ID        uuid.UUID
	Username  string
	DiscordID int32
}

type User struct {
	ID        uuid.UUID
	DiscordID int32
	HiveID    string
	Server    string
	Active    sql.NullBool
	GameUid   int32
}
