// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Coupon struct {
	ID          pgtype.UUID
	Code        string
	Status      string
	FirstSeenAt pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type DiscordUser struct {
	ID        pgtype.UUID
	Username  string
	DiscordID int32
}

type User struct {
	ID        pgtype.UUID
	DiscordID int32
	HiveID    string
	Server    string
	Active    pgtype.Bool
	GameUid   int32
}
