// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Coupon struct {
	ID          uuid.UUID
	Code        string
	Status      string
	FirstSeenAt time.Time
	UpdatedAt   time.Time
}
