// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: redemptions.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type AddRedemptionsParams struct {
	UserID          pgtype.UUID
	CouponID        pgtype.UUID
	Status          string
	ResponseMessage string
}

const getUnclaimedRedemptions = `-- name: GetUnclaimedRedemptions :many

SELECT 
    u.id,
    u.hive_id,
    u.server,
    c.id,
    c.code
FROM
    users u
CROSS JOIN
    coupons c
LEFT JOIN
    redemptions r ON u.id = r.user_id AND r.coupon_id = c.id
WHERE
    r.id IS NULL
`

type GetUnclaimedRedemptionsRow struct {
	ID     pgtype.UUID
	HiveID string
	Server string
	ID_2   pgtype.UUID
	Code   string
}

func (q *Queries) GetUnclaimedRedemptions(ctx context.Context) ([]GetUnclaimedRedemptionsRow, error) {
	rows, err := q.db.Query(ctx, getUnclaimedRedemptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnclaimedRedemptionsRow
	for rows.Next() {
		var i GetUnclaimedRedemptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.HiveID,
			&i.Server,
			&i.ID_2,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
