// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const addUser = `-- name: AddUser :exec
INSERT INTO Users (hive_id, server, discord_id, game_uid) 
VALUES ($1, $2, $3, $4) ON CONFLICT (hive_id, server) DO NOTHING
`

type AddUserParams struct {
	HiveID    string
	Server    string
	DiscordID int32
	GameUid   int32
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) error {
	_, err := q.db.ExecContext(ctx, addUser,
		arg.HiveID,
		arg.Server,
		arg.DiscordID,
		arg.GameUid,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM Users 
WHERE 
    discord_id = $1 AND 
    hive_id = $2 AND  
    server = $3
`

type DeleteUserParams struct {
	DiscordID int32
	HiveID    string
	Server    string
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteUser, arg.DiscordID, arg.HiveID, arg.Server)
}

const getAllUsers = `-- name: GetAllUsers :many
SELECT id, discord_id, hive_id, server, active, game_uid FROM Users
`

func (q *Queries) GetAllUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getAllUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.HiveID,
			&i.Server,
			&i.Active,
			&i.GameUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByHiveCredentials = `-- name: GetUserByHiveCredentials :one
SELECT id, discord_id, hive_id, server, active, game_uid FROM Users WHERE hive_id = $1 AND server = $2
`

type GetUserByHiveCredentialsParams struct {
	HiveID string
	Server string
}

func (q *Queries) GetUserByHiveCredentials(ctx context.Context, arg GetUserByHiveCredentialsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByHiveCredentials, arg.HiveID, arg.Server)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.HiveID,
		&i.Server,
		&i.Active,
		&i.GameUid,
	)
	return i, err
}
